#!/usr/bin/env python3
import sys
import argparse

# get file, read words, get all substrings of max length,
# write to file

# generated by copilot

MAX_LENGTH = 4

def main(input_file, output_file):
    with open(input_file, 'r') as f:
        words = f.read().split()
    substrings = set()
    for word in words:
        for i in range(len(word)):
            for j in range(i+1, min(i+MAX_LENGTH+1, len(word)+1)):
                substrings.add(word[i:j])
    with open(output_file, 'w') as f:
        for substring in substrings:
            f.write(substring + '\n')

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('input_file', type=str)
    parser.add_argument('output_file', type=str)
    args = parser.parse_args()
    main(args.input_file, args.output_file)